name: Build
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - hotfix/*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install .NET SDK 8.0.x, 9.0.x & 10.0.x
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: global.json

      - name: Run Cake script
        uses: cake-build/cake-action@v3
        env:
          NuGetReportSettings_SharedKey: ${{ secrets.NUGETREPORTSETTINGS_SHAREDKEY }}
          NuGetReportSettings_WorkspaceId: ${{ secrets.NUGETREPORTSETTINGS_WORKSPACEID }}
          GH_PACKAGES_NUGET_SOURCE: ${{ secrets.GH_PACKAGES_NUGET_SOURCE }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_USER: ${{ secrets.NUGET_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file-path: cake.cs
          target: GitHub-Actions